
name: CICD workflow

on:
  push:
    branches: [ "main" ]

jobs:
  Compile:

    runs-on: Server-1

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java with Maven
      -uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # or 'zulu', 'adopt'
          java-version: '17'      # Change to your required Java version
          cache: 'maven'

      - name: Compile Java Code
        run: mvn compile


  
