name: CICD workflow

on:
  push:
    branches: [ "main" ]

jobs:
  compile:  # lowercase recommended for job names
    runs-on: Server-1  # Ensure 'Server-1' is a valid/self-hosted runner label

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java with Maven
        uses: actions/setup-java@v4  # Fixed indentation and hyphen
        with:
          distribution: 'temurin'     # or 'zulu', 'adopt'
          java-version: '17'         # Adjust if needed
          cache: 'maven'

      - name: Compile Java Code 
        run: mvn compile  # Corrected indentation and `run` block



  
